import { useState } from 'react';
import { PHeading, PText, PTag, PIcon, PButton, PTabs, PTabsItem, PInlineNotification } from '@porsche-design-system/components-react';
import type { AppState } from '../store/appStore';
import type { Meeting, Priority } from '../types';

const priorityVariant: Record<Priority, 'error' | 'warning' | 'info' | 'secondary'> = {
  critical: 'error', high: 'warning', medium: 'info', low: 'secondary',
};

function MeetingCard({ meeting, onSelect }: { meeting: Meeting; onSelect: (m: Meeting) => void }) {
  const statusColors: Record<Meeting['status'], string> = {
    completed: 'success',
    scheduled: 'info',
    in_progress: 'warning',
    cancelled: 'error',
  };

  return (
    <div
      className="bg-canvas rounded border border-contrast-low p-static-sm space-y-2 cursor-pointer hover:border-primary transition-colors"
      onClick={() => onSelect(meeting)}
    >
      <div className="flex items-start justify-between gap-2">
        <PText size="x-small" weight="semi-bold">{meeting.title}</PText>
        <div className="flex gap-2 shrink-0">
          <PTag variant={statusColors[meeting.status] as 'success' | 'info' | 'warning' | 'error'} compact>
            {meeting.status.replace('_', ' ')}
          </PTag>
          <PTag variant={priorityVariant[meeting.priority]} compact>{meeting.priority}</PTag>
        </div>
      </div>

      <div className="flex items-center gap-3 flex-wrap">
        <div className="flex items-center gap-1">
          <PIcon name="calendar" size="small" color="contrast-medium" />
          <PText size="xx-small" color="contrast-medium">
            {new Date(meeting.date).toLocaleString('en-US', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })}
          </PText>
        </div>
        <div className="flex items-center gap-1">
          <PIcon name="clock" size="small" color="contrast-medium" />
          <PText size="xx-small" color="contrast-medium">{meeting.duration} min</PText>
        </div>
        <div className="flex items-center gap-1">
          <PIcon name="group" size="small" color="contrast-medium" />
          <PText size="xx-small" color="contrast-medium">{meeting.participants.length} participants</PText>
        </div>
      </div>

      <div className="flex items-center gap-2">
        {meeting.aiProcessed && <PTag color="background-frosted" icon="ai-spark" compact>AI Processed</PTag>}
        {meeting.mom && <PTag variant="success" icon="check" compact>MOM Ready</PTag>}
        {meeting.project && <PTag compact>{meeting.project}</PTag>}
      </div>
    </div>
  );
}

function MOMView({ meeting }: { meeting: Meeting }) {
  if (!meeting.mom) return (
    <div className="flex flex-col items-center justify-center py-16 opacity-50">
      <PIcon name="chat" size="large" color="contrast-medium" />
      <PText color="contrast-medium" size="small">MOM not yet generated</PText>
      <PText color="contrast-medium" size="xx-small">Upload a recording to trigger AI processing</PText>
    </div>
  );

  const { mom } = meeting;

  return (
    <div className="space-y-fluid-sm">
      <PInlineNotification
        heading="AI-Generated MOM"
        description="This Minutes of Meeting was automatically generated by the AI pipeline after meeting completion."
        state="info"
        dismissButton={false}
      />

      <div className="bg-canvas rounded border border-contrast-low p-fluid-md space-y-fluid-sm">
        <div>
          <PHeading size="small" tag="h3">{mom.title}</PHeading>
          <PText size="xx-small" color="contrast-medium">
            {new Date(mom.date).toLocaleString()} · Version {mom.version} · Generated automatically
          </PText>
        </div>

        <div>
          <PText size="x-small" weight="semi-bold">Participants</PText>
          <div className="flex flex-wrap gap-2 mt-1">
            {mom.participants.map(p => <PTag key={p} compact>{p}</PTag>)}
          </div>
        </div>

        <div>
          <PText size="x-small" weight="semi-bold">Executive Summary</PText>
          <PText size="x-small" color="contrast-high" tag="p">{mom.summary}</PText>
        </div>

        <div>
          <PText size="x-small" weight="semi-bold">Key Discussion Points</PText>
          <ul className="mt-2 space-y-1">
            {mom.keyPoints.map((point, i) => (
              <li key={i} className="flex items-start gap-2">
                <PIcon name="arrow-compact-right" size="small" color="primary" />
                <PText size="x-small">{point}</PText>
              </li>
            ))}
          </ul>
        </div>

        <div>
          <PText size="x-small" weight="semi-bold">Action Items</PText>
          <div className="space-y-2 mt-2">
            {mom.actionItems.map(item => (
              <div key={item.id} className="flex items-start gap-3 p-static-sm rounded border border-contrast-low bg-surface">
                <PTag variant={priorityVariant[item.priority]} compact>{item.priority}</PTag>
                <div className="flex-1 min-w-0">
                  <PText size="x-small" weight="semi-bold">{item.description}</PText>
                  <div className="flex items-center gap-2 mt-1">
                    <PIcon name="group" size="small" color="contrast-medium" />
                    <PText size="xx-small" color="contrast-medium">{item.owner}</PText>
                    <PIcon name="clock" size="small" color="contrast-medium" />
                    <PText size="xx-small" color="contrast-medium">Due {new Date(item.deadline).toLocaleDateString()}</PText>
                  </div>
                </div>
                <PTag variant={item.taskId ? 'success' : 'info'} compact>
                  {item.taskId ? 'Task Created' : 'Pending'}
                </PTag>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

interface Props { state: AppState }

export default function Meetings({ state }: Props) {
  const [selectedMeeting, setSelectedMeeting] = useState<Meeting | null>(state.meetings[0] ?? null);
  const [activeTab, setActiveTab] = useState(0);

  const completed = state.meetings.filter(m => m.status === 'completed');
  const scheduled = state.meetings.filter(m => m.status === 'scheduled');

  return (
    <div className="flex-1 overflow-hidden flex gap-4 p-fluid-md">
      {/* Meeting list */}
      <aside className="w-80 shrink-0 flex flex-col gap-fluid-sm overflow-y-auto">
        <div className="flex items-center justify-between">
          <PHeading size="small" tag="h2">Meetings</PHeading>
          <PTag color="background-frosted" icon="ai-spark" compact>Auto-Processed</PTag>
        </div>

        <div>
          <PText size="xx-small" weight="semi-bold" color="contrast-medium" tag="p" style={{ textTransform: 'uppercase', letterSpacing: '0.05em', paddingBottom: '8px' }}>
            Scheduled ({scheduled.length})
          </PText>
          <div className="space-y-2">
            {scheduled.map(m => <MeetingCard key={m.id} meeting={m} onSelect={setSelectedMeeting} />)}
          </div>
        </div>

        <div>
          <PText size="xx-small" weight="semi-bold" color="contrast-medium" tag="p" style={{ textTransform: 'uppercase', letterSpacing: '0.05em', paddingBottom: '8px' }}>
            Completed ({completed.length})
          </PText>
          <div className="space-y-2">
            {completed.map(m => <MeetingCard key={m.id} meeting={m} onSelect={setSelectedMeeting} />)}
          </div>
        </div>
      </aside>

      {/* Meeting detail */}
      <main className="flex-1 overflow-y-auto bg-surface rounded-lg border border-contrast-low p-fluid-md">
        {selectedMeeting ? (
          <>
            <div className="flex items-start justify-between gap-4 mb-fluid-sm">
              <div>
                <PHeading size="medium" tag="h2">{selectedMeeting.title}</PHeading>
                <PText size="x-small" color="contrast-medium">
                  {new Date(selectedMeeting.date).toLocaleString()} · {selectedMeeting.duration} min
                </PText>
              </div>
              <div className="flex gap-2 shrink-0">
                {selectedMeeting.status === 'scheduled' && (
                  <PButton variant="secondary" icon="document" compact type="button">Upload Recording</PButton>
                )}
              </div>
            </div>

            <PTabs activeTabIndex={activeTab} onUpdate={e => setActiveTab(e.detail.activeTabIndex)} size="small">
              <PTabsItem label="Overview">
                <div className="pt-2 space-y-fluid-sm">
                  <div className="grid grid-cols-2 gap-3">
                    <div className="p-static-sm rounded border border-contrast-low bg-canvas">
                      <PText size="xx-small" color="contrast-medium">Status</PText>
                      <PText size="x-small" weight="semi-bold">{selectedMeeting.status.replace('_', ' ').toUpperCase()}</PText>
                    </div>
                    <div className="p-static-sm rounded border border-contrast-low bg-canvas">
                      <PText size="xx-small" color="contrast-medium">Priority</PText>
                      <PText size="x-small" weight="semi-bold">{selectedMeeting.priority.toUpperCase()}</PText>
                    </div>
                    {selectedMeeting.project && (
                      <div className="p-static-sm rounded border border-contrast-low bg-canvas">
                        <PText size="xx-small" color="contrast-medium">Project</PText>
                        <PText size="x-small" weight="semi-bold">{selectedMeeting.project}</PText>
                      </div>
                    )}
                  </div>
                  <div>
                    <PText size="x-small" weight="semi-bold">Participants</PText>
                    <div className="flex flex-wrap gap-2 mt-2">
                      {selectedMeeting.participants.map(p => <PTag key={p} compact>{p}</PTag>)}
                    </div>
                  </div>
                </div>
              </PTabsItem>
              <PTabsItem label="MOM & Notes">
                <div className="pt-2">
                  <MOMView meeting={selectedMeeting} />
                </div>
              </PTabsItem>
              <PTabsItem label="Transcription">
                <div className="pt-2">
                  {selectedMeeting.transcription ? (
                    <div className="p-fluid-md rounded border border-contrast-low bg-canvas">
                      <PTag color="background-frosted" icon="ai-spark">AI Transcription</PTag>
                      <PText size="x-small" tag="p" style={{ marginTop: '12px', lineHeight: 1.7 }}>{selectedMeeting.transcription}</PText>
                    </div>
                  ) : (
                    <div className="flex flex-col items-center justify-center py-16 opacity-50">
                      <PIcon name="microphone" size="large" color="contrast-medium" />
                      <PText color="contrast-medium">No transcription available</PText>
                    </div>
                  )}
                </div>
              </PTabsItem>
            </PTabs>
          </>
        ) : (
          <div className="flex flex-col items-center justify-center h-full opacity-50">
            <PIcon name="chat" size="large" color="contrast-medium" />
            <PText color="contrast-medium">Select a meeting to view details</PText>
          </div>
        )}
      </main>
    </div>
  );
}
